services:
  brronson:
    container_name: brronson
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-1968}:${PORT:-1968}"
    environment:
      # Gunicorn configuration
      - PORT=${PORT:-1968}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-4}
      - GUNICORN_LOG_LEVEL=${GUNICORN_LOG_LEVEL:-info}
      # Application configuration
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
      - CLEANUP_DIRECTORY=/data
      - TARGET_DIRECTORY=/target
      - LOG_LEVEL=INFO
      - LOG_FILE=brronson.log
      - LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
